name: Convert Report to PDF

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Report to convert'
        required: true
        type: choice
        # UC Use Case reports based on ReportingFramework
        options:
        - UC-01-Project-Initialization
        - UC-02-Scenario-Creation
        - UC-03-Scenario-Results-RoundTrip
        - UC-04-PK-Parameter-Loading
        - UC-05-Population-Export
        - UC-06-Utilities-Data-Integration
        - UC-07A-Plot-TimeProfiles
        - UC-07B-Plot-PKBoxwhisker
        - UC-07C-Plot-PKForest
        - UC-07D-Plot-Demographics
        - UC-08-Report-Generation
        - UC-09-EPackage-Export
        - UC-10-Sensitivity-Analysis
        - UC-11-Snapshot-Version-Control

jobs:
  report-to-pdf:
    runs-on: ubuntu-latest
    # Allow only authorized collaborators to trigger GA:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
# All steps in workflow:
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Perform html conversion with pandoc
        run: |
          pandoc -f markdown -t html5 --embed-resources --standalone \
          -o Reports/${{ inputs.report }}/Report.html \
          Reports/${{ inputs.report }}/Report.md -c osp.css
      # Run the HTML to PDF converter action
      - name: HTML website to PDF converter
        uses: fifsky/html-to-pdf-action@e9cd233673371568821ec94052c6989b33d8f032
        with:
          htmlFile: ./Reports/${{ inputs.report }}/Report.html
          outputFile: ./Reports/${{ inputs.report }}/Report.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}, "displayHeaderFooter": true, "headerTemplate": "<span></span>", "footerTemplate": "<span style=\"font-size: 12px;\">&emsp;&emsp;Page <span class=\"pageNumber\"></span> / <span class=\"totalPages\"></span></span>"}'

      - name: Save PDF file as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.report }}-pdf
          path: Reports/${{ inputs.report }}
